spring.application.name=Hogwarts

spring.datasource.url=jdbc:postgresql://hog2.cwie5mcas8te.us-east-1.rds.amazonaws.com:5432/hogwarts
spring.datasource.username=postgres
spring.datasource.password=postgres


spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jackson.serialization.fail-on-empty-beans=false
